language: python

python:
  - "3.6"

service:
  - postgresql

install:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - source example.env
  - pip install --editable .
