language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE mtracker_test;" -U postgres
  - psql -c "CREATE DATABASE mtracker;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - export PGUSER="postgres"
  - export PGDATABASE="mtracker"
  - export PGPASSWORD="password"
  - export APP_SETTINGS="api.server.config.TestingConfig"
  - export SECRET_KEY="justatest"


install:
  - pip install -r requirements.txt

before_script:
  
  - pip install --editable .
  - mtracker create db
  - mtracker create schema
  - mtracker create test-schema

script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=api/server
  - coveralls

after_success:
  - "coveralls"