language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE mtracker_test;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - export APP_SETTINGS="api.server.config.TestingConfig"
  - export SECRET_KEY="this_is_the_secret_key"
  - export PGDATABASE="mtracker_test"
  - export PGUSER="postgres"
  - export PGPASSWORD="password"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - python migrate.py

script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=api/server
  - coveralls

after_success:
  - "coveralls"